### ISSUE TITLE
Please expose current reward as external function

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/tellorX#10]
Internally making it as a separate function and making it external shouldn't increase the gas by much, but it will add a great convenience for when writing the submit logic of the client.

**Comment by krasi-georgiev** [comment]
Since this we be a gas war game having this exported will ensure people can calculate more accurately when it will be profitable to submit.

**Comment by tallywiesenberg** [comment]
I added a getter for the time based reward, please let me know if this is what you were referring to!
