### ISSUE TITLE
add a getter for the current dispute fee for a  given data ID

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/tellorX#107]
as a reporter I would need to know how much a dispute would cost before actually opening it and there is no getter for that.

**Comment by krasi-georgiev** [comment]
yes correct, but what is the reason for not adding a getter in the tellorX contacts?

**Comment by tkernell** [comment]
We're trying to limit the size of the core tellorX contracts. We also just need to draw a line in the sand and finalize the contracts so we can upgrade Rinkeby tellor and then finally mainnet. There will always be an endless list of things that can be improved, but we have to call it at some point. If we find any bugs of course we'll need to fix those and extend our timeline, but at this point we seem to be in a good place to finalize everything.

**Comment by krasi-georgiev** [comment]
When you build the GUI for opening disputes this will make the implementation more difficult and will triple the infura calls.
