### ISSUE TITLE
Add reporter address to the NewReport event

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/tellorX#114]
When querying past submitted values it makes sense that the NewReport event also includes the reporter address.

**Comment by tkernell** [comment]
We will save this note for a future upgrade

**Comment by krasi-georgiev** [comment]
This is a single change and no security risk, why wait for the next upgrade? For the the logic I use in the software that monitor the report events this is an important data and this existed in the old submitMiningSolution event.
