### ISSUE TITLE
How to time treasury issuance

### ISSUE THREAD

**Issue by tallywiesenberg** [tellor-io/tellorX#12]
Can governance approve of multiple time-overlapping treasury issuances? Can governance issue a new round of treasuries before buyers purchase ALL of the remaining treasuries?

**Comment by tkernell** [comment]
Maybe keep it flexible by allowing overlapping treasuries? Especially if treasuries are meant for dampening price fluctuations and we see some major price fluctuations right in the middle of a smaller treasury issuance. We may want to start a new larger treasury then. And the friction of querying the treasury count and inputing a treasury id can be handled on the frontend

**Comment by tallywiesenberg** [comment]
I agree. I think our current design makes the front end a little messier, and will require more educational maintenance, but functionally will accomplish the mission of the Treasury.
