### ISSUE TITLE
Add disputer and reporter addresses to the tallyVotes event

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/tellorX#122]
In my reporter implementation, I monitor these events to schedule automatic dispute execute TXs. The dispute and reporter address was part of the  tallyVotes event  in tellor3

**Comment by themandalore** [comment]
Code's frozen now, so this doesn't qualify.  But next version.  With tellor3 though, there's 5 miners on a value,  now theres only 1 so the look up isn't bad at all for a rare event
