### ISSUE TITLE
add events for the contract update functions

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/tellorX#123]
changeControllerContract, 
changeGovernanceContract
changeOracleContract
changeTreasuryContract

without events on these calls I can't think of an easy way to monitor when an upgrade happened

**Comment by themandalore** [comment]
yeah, we can add events.  But hopefully the community doesn't need events to let them know these are happening

**Comment by tkernell** [comment]
In the meantime, the `NewVote` event can be used, filtering with the `bytes4 _function` argument

**Comment by krasi-georgiev** [comment]
yes I know there is a workaround, but adding an event simplifies quite a bit of the monitoring logic.

**Comment by krasi-georgiev** [comment]
> But hopefully the community doesn't need events to let them know these are happening

@themandalore not sure what you mean by this?
