### ISSUE TITLE
Separate the logic for disputes and votes

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/tellorX#125]
using different variables and events

splitting this logic will reduce the monitoring the tests complexity

There is quite a bit of overlap, but also few variables that are specific to just voting and just disputes to splitting those would make the code easier to follow

**Comment by themandalore** [comment]
maybe for another upgrade,  really don't think it's too much of an issue, but open to arguments

**Comment by krasi-georgiev** [comment]
yes deff for the next upgrade and yes lets discuss in discord when the time comes.
