### ISSUE TITLE
Make the report submit nonce a global counter or make it optional

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/tellorX#133]
When 2 tx for different query ID end up in the same block or with very small time apart the second one will still pass causing the reporter to not get any rewards and loose money for the TX.

**Comment by clamdad** [comment]
Is it possible/worthwhile to recognize the situation and attempt to cancel the losing submission?

**Comment by krasi-georgiev** [comment]
not enough time for this. I think making it global and optional will also solve the linked issue
