### ISSUE TITLE
Differentiating between `VoteResult` and `_invalidQuery`

### ISSUE THREAD

**Issue by cpondoc** [tellor-io/tellorX#28]
The enum `VoteResult` is expected to help account for all states of a vote: `FAILED`, `PASSED`, and now `INVALID`. However, there still exists an `_invalidQuery` function within the external and internal vote functions, and the `Vote` struct also contains a `uint256 invalidQuery`.

In the future, we can look at streamlining the code by potentially changing the vote functions’ functionalities to remove the `_invalidQuery` and use the Vote’s `VoteResult result` property.

**Comment by tkernell** [comment]
Those are some good thoughts, Chris. I think the current design may still be needed because we have two types of votes: proposals and disputes. `INVALID` results only apply to disputes and not to proposals, and keeping a `_supports` bool prevents proposal voters from only choosing `INVALID`.
