### ISSUE TITLE
Audit Finding (Treasury)

### ISSUE THREAD

**Issue by themandalore** [tellor-io/tellorX#42]
Investors can buy right before the treasury duration ends and get the full rate.
Also an investor that has bought treasury at the beginning and not voted (even once), they can but 1 more token and reset their startVoteCount to bypass the penalty logic in Treasury.sol#L131-148
The only protection I can see is the totalAmount (which I would change to maxAmount btw) and investors would not be able to buy at the end.
However, the investor can buy 0 amount 🙂

**Comment by themandalore** [comment]
Also, the investor can rebuy the same treasury after paying back and loose their tokens, because second payback is not possible (`paid` variable).

**Comment by tkernell** [comment]
"Investors can buy right before the treasury duration ends and get the full rate." 
- For this one, shouldn't we expect that people will race each other to buy treasuries? Someone waiting until the end will be beaten by someone who buys up all of the treasuries before them. Treasury investors are facing a prisoner's dilemma in that they would all be better off waiting until the very end of the treasury duration to actually buy treasuries, but they can't commit to following this strategy. People are incentivized to defect and buy treasuries before they're all gone.

**Comment by damianrusinek** [comment]
Besides
1. You add `msg.sender` multiple times to `owners` (on multiple `buyTreasury` calls).
2. I would change the `totalAmount` to `maxAmount` and `purchased` to `purchasedAmount`. People may be used to treat `totalAmount` as the current amount like in tokens - this is to make the code clearer only (no security issue).

**Comment by damianrusinek** [comment]
Looks good 👍
