### ISSUE TITLE
Reduce _STAKE_COUNT when slashing reporter

### ISSUE THREAD

**Issue by tkernell** [tellor-io/tellorX#44]
When a `PASSED` dispute is executed and a miner is slashed, it doesn't appear that `_STAKE_COUNT` is reduced, nor is `updateDisputeFee` called. Shouldn't this be added?

**Comment by themandalore** [comment]
it should be on the beginDispute .... it should go up as miners are taken out via dispute...great Catch!

**Comment by tkernell** [comment]
https://github.com/tellor-io/tellorX/pull/46

**Comment by tkernell** [comment]
Contracts updated
